version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=mydeploy_password
      - MYSQL_DATABASE=mydeploy
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
